name: ada-project
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.23.1
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - scikit-learn=1.1.2
  - statsmodels=0.14.0
  - jupyter=1.0.0
